[general]
import = [
    "~/.config/alacritty/themes/tokyo-night/tokyonight_night.toml"
]

[window]
dynamic_padding = true

[selection]
save_to_clipboard = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001F"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u001F"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
